# pipeline parameters
fullpipeline: true
maponly: false
cageronly: false
gtf: "assets/sacCer3_genome/sacCer3.ensGene.gtf"

# preprocessing parameters
samplesheet: "assets/samplesheet_sacer_pe_template_for_GA.csv"
infolder:
sample_name_fields:
genome_name: "sacCer3"
fasta: "assets/sacCer3_genome/sacCer3.fa"
index: "assets/sacCer3_genome/sacCer3_star_index/"
star_ignore_sjdbgtf: false
seq_platform: "illumina"
seq_center: false
# whether to take the uniquely mapped only
unique_only: false

# CAGEr parameters
cager_sample_file: "assets/sample_list.csv" # with sorted list of bigwigs, if mapping is run elsewhere
# BSgenome
forgeseed:
sourcedir:
bsgenome: "BSgenome.Scerevisiae.UCSC.sacCer3"
# parameter for correlation calculation
corrplot_tagCountThreshold: 1
# correlation plotting of 10+ samples
heatmap_cex_row: 0.2
# parameters for normalization
norm_range_min: 5
norm_range_max: 10000
norm_method: "powerLaw"
T_norm: 1000000
# parameters for tag clustering
sample_num_thr: 1
ctss_thr: 1
distclu_maxDist: 20
keepSingletonsAbove: 5
# plotting for tagclusters QC
iqw_tpm_threshold: 3
tssregion_up: -3000
tssregion_down: 3000
tsslogo_upstream: 35
# parameters for consensus clusters
consensus_ctss_thr: 2
consensus_ctss_dist: 100
pca_rank: 50