samplesheet: "customcageq/assets/samplesheet_sacer_pe_template_for_GA.csv"
infolder:
bsgenome: "BSgenome.Scerevisiae.UCSC.sacCer3"
gene_annotation: "TxDb.Scerevisiae.UCSC.sacCer3.sgdGene"
genome_annotation: "org.Sc.sgd.db"
forgeseed:
sourcedir:
fasta:
gtf: "customcageq/assets/sacCer3_genome/sacCer3.ensGene.gtf"
index: "customcageq/assets/sacCer3_genome/sacCer3_star_index/"
# chromsizes: "assets/sacCer3_genome/sacCer3.chrom.sizes"
# CAGEr parameters
# annotation: "TxDb.Hsapiens.UCSC.hg38.knownGene"
# annot_db: "org.Hs.eg.db"
tpm_threshold: 1
tagcluster_qc_pdf_height: 5
tagcluster_qc_pdf_width: 4
# parameters for normalization
norm_range_min: 10
norm_range_max: 10000
norm_method: "powerLaw"
total_tag_num: 1000000
